language: node_js

os: linux
dist: jammy

node_js:
  - "10.14.2"
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - wget http://ftp.ubuntu.com/ubuntu/pool/universe/d/docker-buildx/docker-buildx_0.11.2-0ubuntu2_amd64.deb
  - sudo dpkg -i docker-buildx_0.11.2-0ubuntu2_amd64.deb
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - docker pull docker.io/docker/dockerfile:experimental
  - docker pull docker.io/library/node:10.14.2-alpine
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn install --frozen-lockfile

addons:
  artifacts:
    region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /
  chrome: stable
  packages:


services:
  - docker

script:
  - npm test
  - ./artifact.sh

jobs:
  allow_failures:
    - node_js: node
